name: Attempt a build with Gradle

on:
  pull_request:
    branches: [main]

jobs:
  run-initialize-sh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Install system-wide LibSodium
        run: sudo apt-get install -y libsodium-dev

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Initialize submodule, generate jars, and build (including tests)
        run: chmod +x initialize.sh && ./initialize.sh
