name: Run Gradle Test

on:
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install system-wide LibSodium
        run: sudo apt-get install -y libsodium-dev

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Wrapper
        run: chmod +x gradlew && gradle wrapper

      - name: Initialize Repo and Jars
        run: chmod +x initialize.sh && ./initialize.sh

      - name: Run tests
        run: ./gradlew test

      - name: Run build
        run: ./gradlew build
